version: '3'

services:

  work:
    build:
      context: .
      dockerfile: Dockerfile
      args: [ 'HGID=${HGID}','HUID=${HUID}' ]
    image: mamemomonga/awscli-env

    volumes:
       - './ubuntu:/home/ubuntu'

    hostname: awscli-env
    working_dir: /root

